accounts:
  - name: colt
    coins: ["20000token", "200000000stake"]
    mnemonic: "train okay curtain host enact attend boring phone chest news always dress renew buyer empower toss grape vacuum lion squeeze fly fluid surge kiss"
  - name: dave
    coins: ["10000token", "100000000stake"]
    mnemonic: "define envelope federal move soul panel purity language memory illegal little twin borrow menu mule vote alter bright must deal sight muscle weather rug"
validator:
  name: colt
  staked: "100000000stake"
client:
  vuex:
    path: "vue/src/store"
  openapi:
    path: "docs/static/openapi.yml"
faucet:
  name: dave
  coins: ["5token", "100000stake"]
genesis:
  chain_id: "leaderboard"